# Generated by Django 4.2.13 on 2026-04-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventario',
            table=None,
        ),
        migrations.AlterModelTable(
            name='producto',
            table=None,
        ),
    ]
