# Generated by Django 4.2.13 on 2026-04-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pedido_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo/Presencial')], default='transferencia', max_length=20),
        ),
    ]
