# Generated by Django 4.2.13 on 2026-04-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pedido_correo_cliente_pedido_nombre_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='sucursal',
            field=models.CharField(choices=[('linares_catedral', 'Linares Catedral'), ('linares_hospital', 'Linares Hospital'), ('talca', 'Sucursal Talca')], default='linares_catedral', max_length=50),
        ),
    ]
